// ============================================================
// lib/products.ts — カグエラ 商品データベース
// ============================================================

export type Category = 'furniture' | 'appliance';

export type SubCategory =
  // 家具
  | 'sofa' | 'bed' | 'desk' | 'chair' | 'dining_table' | 'shelf' | 'wardrobe' | 'tv_stand'
  // 家電
  | 'refrigerator' | 'tv' | 'microwave' | 'washing_machine'
  | 'air_conditioner' | 'vacuum' | 'rice_cooker' | 'kettle';

export type Style = 'modern' | 'natural' | 'minimal' | 'cozy' | 'industrial';

export type Product = {
  id: string;
  name: string;
  category: Category;
  subCategory: SubCategory;
  price: number;
  condition: 'new' | 'used';
  shopName: string;
  size: {
    width: number;  // cm
    depth: number;  // cm
    height: number; // cm
  };
  color: string;    // HEXコード
  imageUrl: string; // Unsplash URL
  icon: string;     // 上から見た絵文字
  description: string;
  style: Style[];
  essentialForSingle: boolean;
  // 参考データベース（1sya / 2sya / A / B / C社）由来の追加属性
  rating?: number;     // 0.0〜5.0
  texture?: string;    // 質感（例: 無垢材、ステンレス、布地）
  atmosphere?: string; // 雰囲気（例: モダン、レトロ、高級感）
};

// ============================================================
// 商品データ (58件)
// new : used ≒ 7 : 3
// ============================================================

export const products: Product[] = [

  // ───────────────────────────── ソファ (6) ─────────────────────────────

  {
    id: 'sofa-001',
    name: 'スタンダード 2人掛けソファ',
    category: 'furniture',
    subCategory: 'sofa',
    price: 45800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 155, depth: 85, height: 78 },
    color: '#A0906E',
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=400&q=80',
    icon: '🛋️',
    description: 'シンプルなラインが美しいファブリックソファ。一人暮らしのリビングにちょうど良い2人掛けサイズ。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-002',
    name: 'コーナーソファ L字型',
    category: 'furniture',
    subCategory: 'sofa',
    price: 89000,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 220, depth: 85, height: 80 },
    color: '#6B6B6B',
    imageUrl: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=400&q=80',
    icon: '🛋️',
    description: 'ゆったりと寛げるL字型コーナーソファ。大型でも脚がスリムなため圧迫感を抑えたデザイン。',
    style: ['modern', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-003',
    name: 'ローソファ コンパクト',
    category: 'furniture',
    subCategory: 'sofa',
    price: 38500,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 140, depth: 80, height: 70 },
    color: '#D4B896',
    imageUrl: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=400&q=80',
    icon: '🛋️',
    description: '座面高が低くナチュラルな雰囲気のローソファ。フロアスタイルのリビングにおすすめ。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-004',
    name: 'ファブリック 3人掛けソファ',
    category: 'furniture',
    subCategory: 'sofa',
    price: 74800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 205, depth: 88, height: 82 },
    color: '#8E9B8E',
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=400&q=80',
    icon: '🛋️',
    description: '落ち着いたグリーングレーが人気の3人掛けソファ。美品中古でコストを抑えて上質なリビングを実現。',
    style: ['cozy', 'natural'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-005',
    name: 'レザー調 2.5人掛けソファ',
    category: 'furniture',
    subCategory: 'sofa',
    price: 96000,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 185, depth: 90, height: 85 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=400&q=80',
    icon: '🛋️',
    description: 'マットなブラックレザー調素材が存在感を放つソファ。スチール脚との組み合わせがインダストリアルな空間にマッチ。',
    style: ['industrial', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-006',
    name: '1人掛けソファチェア',
    category: 'furniture',
    subCategory: 'sofa',
    price: 27800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 75, depth: 80, height: 75 },
    color: '#C4A882',
    imageUrl: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=400&q=80',
    icon: '🪑',
    description: 'コンパクトな1人掛けソファ。読書や作業のお供に。狭いワンルームでも圧迫感なく置ける。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ベッド (6) ─────────────────────────────

  {
    id: 'bed-001',
    name: 'シングルベッドフレーム 木脚',
    category: 'furniture',
    subCategory: 'bed',
    price: 34800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 100, depth: 205, height: 80 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
    icon: '🛏️',
    description: '天然木の脚がやさしい印象を与えるシングルフレーム。ヘッドボードにコンセント付き。',
    style: ['natural', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'bed-002',
    name: 'ダブルベッド フラットデザイン',
    category: 'furniture',
    subCategory: 'bed',
    price: 67500,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 145, depth: 210, height: 75 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80',
    icon: '🛏️',
    description: 'ミニマルなホワイトフレームのダブルベッド。ローヘッドボードで天井が高く見えるデザイン。',
    style: ['modern', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'bed-003',
    name: 'セミダブル すのこベッド',
    category: 'furniture',
    subCategory: 'bed',
    price: 22800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 120, depth: 200, height: 35 },
    color: '#C4A882',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80',
    icon: '🛏️',
    description: '通気性抜群のすのこ仕様。湿気が多い日本の気候にぴったり。中古美品でお得に入手。',
    style: ['natural'],
    essentialForSingle: true,
  },
  {
    id: 'bed-004',
    name: '収納付き シングルベッド',
    category: 'furniture',
    subCategory: 'bed',
    price: 81000,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 100, depth: 210, height: 90 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
    icon: '🛏️',
    description: 'ベッド下に大容量の引き出し収納付き。衣類や寝具のしまい場所に困るワンルームに最適。',
    style: ['natural', 'cozy'],
    essentialForSingle: true,
  },
  {
    id: 'bed-005',
    name: 'ローベッド ウォールナット調',
    category: 'furniture',
    subCategory: 'bed',
    price: 47800,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 100, depth: 205, height: 30 },
    color: '#4A3728',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80',
    icon: '🛏️',
    description: 'ダークウォールナット調の落ち着いたローベッド。床に近い設計で部屋を広く見せる効果あり。',
    style: ['industrial', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'bed-006',
    name: 'パイプベッド シンプル',
    category: 'furniture',
    subCategory: 'bed',
    price: 18500,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 100, depth: 200, height: 85 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80',
    icon: '🛏️',
    description: 'スチールパイプ製のシンプルベッド。軽量で組み立て・分解が簡単。引越しが多い方に。',
    style: ['industrial', 'minimal'],
    essentialForSingle: true,
  },

  // ───────────────────────────── 机 (5) ────────────────────────────────

  {
    id: 'desk-001',
    name: 'シンプル学習デスク 120cm',
    category: 'furniture',
    subCategory: 'desk',
    price: 19800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 120, depth: 60, height: 72 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80',
    icon: '🪵',
    description: 'ホワイトトップのシンプルな学習デスク。テレワークにも対応した広めの天板。',
    style: ['minimal', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'desk-002',
    name: 'L字デスク コーナー型',
    category: 'furniture',
    subCategory: 'desk',
    price: 44800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 140, depth: 70, height: 75 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80',
    icon: '🪵',
    description: '部屋のコーナーを有効活用するL字デスク。PC作業とサブモニター設置を両立できる広い作業スペース。',
    style: ['industrial', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'desk-003',
    name: '天然木パイン材デスク',
    category: 'furniture',
    subCategory: 'desk',
    price: 37800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 110, depth: 55, height: 72 },
    color: '#C8A87A',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
    icon: '🪵',
    description: '節のある天然パイン材を使用した温かみのあるデスク。木の香りが心地よい作業環境を作る。',
    style: ['natural', 'cozy'],
    essentialForSingle: true,
  },
  {
    id: 'desk-004',
    name: '折りたたみ壁付けデスク',
    category: 'furniture',
    subCategory: 'desk',
    price: 12800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 80, depth: 50, height: 75 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80',
    icon: '🪵',
    description: '使わないときは折りたたんで壁にフラットに収納できるコンパクトデスク。極小スペース向け。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'desk-005',
    name: 'スタンディングデスク 昇降式',
    category: 'furniture',
    subCategory: 'desk',
    price: 64800,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 120, depth: 60, height: 75 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80',
    icon: '🪵',
    description: '電動昇降で座りと立ちを手軽に切り替えられるスタンディングデスク。長時間のテレワークに。',
    style: ['modern', 'industrial'],
    essentialForSingle: true,
  },

  // ───────────────────────────── チェア (5) ────────────────────────────

  {
    id: 'chair-001',
    name: 'メッシュワークチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 27800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 60, depth: 60, height: 90 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400&q=80',
    icon: '🪑',
    description: '通気性に優れたメッシュバックのワークチェア。長時間の作業でも蒸れにくく快適。',
    style: ['modern', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'chair-002',
    name: '木製ダイニングチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 11800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 45, depth: 48, height: 80 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80',
    icon: '🪑',
    description: 'スタッキング可能な天然木のダイニングチェア。シンプルなフォルムでどんなテーブルにも合う。',
    style: ['natural', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'chair-003',
    name: 'ゲーミングチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 42800,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 55, depth: 55, height: 88 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=400&q=80',
    icon: '🪑',
    description: '腰と首をしっかりサポートするゲーミングチェア。リクライニング・アームレスト高さ調整機能付き。',
    style: ['industrial'],
    essentialForSingle: false,
  },
  {
    id: 'chair-004',
    name: 'プラスチックスタッキングチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 4800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 52, depth: 46, height: 80 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400&q=80',
    icon: '🪑',
    description: '軽くて積み重ねられるプラスチックチェア。来客用に複数枚揃えておくのに便利。',
    style: ['minimal'],
    essentialForSingle: false,
  },
  {
    id: 'chair-005',
    name: 'クッションファブリックチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 16800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 55, depth: 55, height: 85 },
    color: '#D4B896',
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80',
    icon: '🪑',
    description: 'ふかふかのシートクッションで座り心地抜群。ダイニングはもちろんリビングにも溶け込むデザイン。',
    style: ['cozy', 'natural'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ダイニングテーブル (4) ───────────────

  {
    id: 'dining-001',
    name: '正方形ダイニングテーブル 75cm',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 28800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 75, depth: 75, height: 72 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1617098474202-0d0d7f60c56b?w=400&q=80',
    icon: '🍽️',
    description: '1〜2人用のコンパクトな正方形テーブル。一人暮らしの食卓にちょうど良いサイズ。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'dining-002',
    name: '伸長式ダイニングテーブル',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 56800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 110, depth: 75, height: 72 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1617098474202-0d0d7f60c56b?w=400&q=80',
    icon: '🍽️',
    description: '普段は2人用、来客時は4人対応に拡張できる伸長式テーブル。ホワイト天板でスペースを明るく。',
    style: ['modern', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'dining-003',
    name: '丸型ローテーブル',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 19800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 80, depth: 80, height: 38 },
    color: '#C8A87A',
    imageUrl: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&q=80',
    icon: '🍽️',
    description: '座椅子に合わせたローテーブル。丸いフォルムが部屋を柔らかい印象にする。',
    style: ['cozy', 'natural'],
    essentialForSingle: false,
  },
  {
    id: 'dining-004',
    name: 'スチール脚ダイニングテーブル',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 72000,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 150, depth: 80, height: 72 },
    color: '#4A3728',
    imageUrl: 'https://images.unsplash.com/photo-1617098474202-0d0d7f60c56b?w=400&q=80',
    icon: '🍽️',
    description: 'ダークウッドの天板×ブラックスチール脚のインダストリアルテーブル。4〜6人対応の大型サイズ。',
    style: ['industrial'],
    essentialForSingle: false,
  },

  // ───────────────────────────── シェルフ (4) ──────────────────────────

  {
    id: 'shelf-001',
    name: 'スチールラック 5段',
    category: 'furniture',
    subCategory: 'shelf',
    price: 14800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 90, depth: 35, height: 180 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=400&q=80',
    icon: '📚',
    description: '高さ調整可能なスチールラック。キッチン・書斎・クローゼット内など用途を選ばない万能棚。',
    style: ['industrial', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'shelf-002',
    name: '天然木 本棚 4段',
    category: 'furniture',
    subCategory: 'shelf',
    price: 24800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 80, depth: 30, height: 150 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80',
    icon: '📚',
    description: '温かみのある天然木の本棚。A4サイズの書類や文庫本がたっぷり収まる4段構成。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'shelf-003',
    name: 'キューブラック 9マス',
    category: 'furniture',
    subCategory: 'shelf',
    price: 11500,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 110, depth: 30, height: 110 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=400&q=80',
    icon: '📚',
    description: 'キューブ型の9マスシェルフ。横置き・縦置き両対応で、バスケットや扉を追加でカスタマイズ可能。',
    style: ['minimal', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'shelf-004',
    name: 'ウォールシェルフセット',
    category: 'furniture',
    subCategory: 'shelf',
    price: 8800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 60, depth: 15, height: 20 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=400&q=80',
    icon: '📚',
    description: '壁に取り付けるフローティングシェルフ3枚セット。床面積を取らず空間を立体的に使える。',
    style: ['minimal', 'natural'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ワードローブ (3) ─────────────────────

  {
    id: 'wardrobe-001',
    name: 'スリムワードローブ 幅80',
    category: 'furniture',
    subCategory: 'wardrobe',
    price: 33800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 80, depth: 50, height: 185 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
    icon: '🚪',
    description: '奥行きスリムで廊下や寝室のデッドスペースに設置しやすいワードローブ。上段に棚付き。',
    style: ['minimal', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'wardrobe-002',
    name: '引き戸ワードローブ 幅120',
    category: 'furniture',
    subCategory: 'wardrobe',
    price: 63000,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 120, depth: 55, height: 200 },
    color: '#D4B896',
    imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
    icon: '🚪',
    description: '引き戸式で前方スペースを取らない大容量ワードローブ。内部はハンガーポール＋引き出し。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'wardrobe-003',
    name: 'ビンテージウッドクローゼット',
    category: 'furniture',
    subCategory: 'wardrobe',
    price: 44800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 100, depth: 55, height: 190 },
    color: '#4A3728',
    imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
    icon: '🚪',
    description: '使い込まれたダークウッドの味わいが魅力のビンテージスタイルクローゼット。中古品。',
    style: ['industrial', 'cozy'],
    essentialForSingle: false,
  },

  // ───────────────────────────── TVボード (3) ──────────────────────────

  {
    id: 'tvstand-001',
    name: 'ローボード 150cm',
    category: 'furniture',
    subCategory: 'tv_stand',
    price: 24800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 150, depth: 40, height: 40 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&q=80',
    icon: '📺',
    description: 'スリムなローボードタイプのTVスタンド。引き出し×2・オープン棚×2でAV機器をすっきり収納。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'tvstand-002',
    name: '壁面TVボード 200cm',
    category: 'furniture',
    subCategory: 'tv_stand',
    price: 54000,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 200, depth: 38, height: 48 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1615874694520-474822394e73?w=400&q=80',
    icon: '📺',
    description: 'フルフラットなブラックの壁面TVボード。壁掛け風の重厚感を床置きで実現できる。',
    style: ['modern', 'industrial'],
    essentialForSingle: false,
  },
  {
    id: 'tvstand-003',
    name: 'ナチュラル木製TVスタンド',
    category: 'furniture',
    subCategory: 'tv_stand',
    price: 17500,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 100, depth: 35, height: 42 },
    color: '#C8A87A',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80',
    icon: '📺',
    description: '明るいナチュラル木目が部屋を明るく見せるTVスタンド。小型TVまで対応。中古美品。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },

  // ───────────────────────────── 冷蔵庫 (4) ───────────────────────────

  {
    id: 'fridge-001',
    name: '2ドア冷蔵庫 139L',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 38800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 50, depth: 60, height: 130 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&q=80',
    icon: '🧊',
    description: '一人暮らしにちょうどいい139Lの2ドア冷蔵庫。右開き。静音設計で寝室隣に置いても安心。',
    style: ['minimal', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'fridge-002',
    name: '1ドアミニ冷蔵庫 45L',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 19800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 48, depth: 45, height: 50 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400&q=80',
    icon: '🧊',
    description: 'デスク横にも置けるコンパクトなミニ冷蔵庫。ドリンクや小物の保冷に。音もほぼ無音。',
    style: ['minimal'],
    essentialForSingle: false,
  },
  {
    id: 'fridge-003',
    name: '3ドア冷蔵庫 300L',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 89000,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 60, depth: 65, height: 165 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1536353284924-9220c464e262?w=400&q=80',
    icon: '🧊',
    description: '野菜室・冷凍庫が独立した3ドアタイプ。自炊派にうれしい大容量。中古美品でお値打ち価格。',
    style: ['modern'],
    essentialForSingle: true,
  },
  {
    id: 'fridge-004',
    name: '2ドア冷蔵庫 170L 右開き',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 52000,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 52, depth: 61, height: 150 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&q=80',
    icon: '🧊',
    description: 'マットブラックのスタイリッシュな冷蔵庫。170Lで一人暮らしには十分な容量。LEDライト内蔵。',
    style: ['modern', 'industrial'],
    essentialForSingle: true,
  },

  // ───────────────────────────── テレビ (4) ────────────────────────────

  {
    id: 'tv-001',
    name: '32インチ フルHD液晶TV',
    category: 'appliance',
    subCategory: 'tv',
    price: 28800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 73, depth: 9, height: 46 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&q=80',
    icon: '📺',
    description: '一人暮らしの定番サイズ32インチ。薄型ベゼルで同サイズより画面が大きく見えるデザイン。',
    style: ['minimal', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'tv-002',
    name: '43インチ 4K スマートTV',
    category: 'appliance',
    subCategory: 'tv',
    price: 48000,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 97, depth: 8, height: 61 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1558888401-3cc1de77652d?w=400&q=80',
    icon: '📺',
    description: 'NetflixやYouTubeをそのまま楽しめる4Kスマートテレビ。43インチで迫力の映像体験。',
    style: ['modern'],
    essentialForSingle: true,
  },
  {
    id: 'tv-003',
    name: '55インチ 有機EL TV',
    category: 'appliance',
    subCategory: 'tv',
    price: 132000,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 122, depth: 8, height: 76 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400&q=80',
    icon: '📺',
    description: '圧倒的なコントラストの有機EL。映画・ゲームを最高画質で楽しみたい方へ。',
    style: ['modern'],
    essentialForSingle: false,
  },
  {
    id: 'tv-004',
    name: '50インチ スマートTV 中古',
    category: 'appliance',
    subCategory: 'tv',
    price: 38000,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 112, depth: 9, height: 70 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&q=80',
    icon: '📺',
    description: '50インチの大画面スマートTVが中古でお値打ち価格。動作確認済み。Wi-Fi対応。',
    style: ['modern'],
    essentialForSingle: true,
  },

  // ───────────────────────────── 電子レンジ (3) ────────────────────────

  {
    id: 'microwave-001',
    name: '単機能電子レンジ 17L',
    category: 'appliance',
    subCategory: 'microwave',
    price: 9800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 44, depth: 34, height: 26 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=400&q=80',
    icon: '📦',
    description: 'シンプルなダイヤル式の単機能レンジ。温めるだけでOKなシンプル志向の方に。コスパ抜群。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'microwave-002',
    name: 'オーブンレンジ 23L',
    category: 'appliance',
    subCategory: 'microwave',
    price: 26800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 49, depth: 39, height: 32 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&q=80',
    icon: '📦',
    description: 'レンジとオーブンが一台で。グラタン・トーストもお任せ。フラットテーブルでお手入れ簡単。',
    style: ['modern'],
    essentialForSingle: true,
  },
  {
    id: 'microwave-003',
    name: 'スチームオーブンレンジ 26L 中古',
    category: 'appliance',
    subCategory: 'microwave',
    price: 21800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 50, depth: 40, height: 35 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585237017125-24baf8d7406f?w=400&q=80',
    icon: '📦',
    description: 'スチーム機能付きで健康的な調理ができる高機能レンジ。中古でもほぼ新品のコンディション。',
    style: ['modern'],
    essentialForSingle: true,
  },

  // ───────────────────────────── 洗濯機 (3) ───────────────────────────

  {
    id: 'wash-001',
    name: '全自動洗濯機 6kg',
    category: 'appliance',
    subCategory: 'washing_machine',
    price: 45800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 56, depth: 55, height: 93 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400&q=80',
    icon: '🫧',
    description: '一人暮らしに最適な6kgの全自動洗濯機。黒カビを抑える抗菌コートドラム採用。',
    style: ['minimal', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'wash-002',
    name: 'ドラム式洗濯乾燥機 8kg',
    category: 'appliance',
    subCategory: 'washing_machine',
    price: 112000,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 60, depth: 65, height: 100 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&q=80',
    icon: '🫧',
    description: '乾燥まで全自動のドラム式。花粉シーズンや梅雨でも部屋干し不要で快適な生活を実現。',
    style: ['modern'],
    essentialForSingle: true,
  },
  {
    id: 'wash-003',
    name: 'コンパクト洗濯機 4kg 中古',
    category: 'appliance',
    subCategory: 'washing_machine',
    price: 18500,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 53, depth: 49, height: 85 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?w=400&q=80',
    icon: '🫧',
    description: '洗濯頻度が高い一人暮らしの方に。4kgのコンパクトサイズで毎日小まめに回せる。中古品。',
    style: ['minimal'],
    essentialForSingle: true,
  },

  // ───────────────────────────── エアコン (2) ──────────────────────────

  {
    id: 'ac-001',
    name: 'エアコン 6畳用 冷暖房',
    category: 'appliance',
    subCategory: 'air_conditioner',
    price: 52800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 80, depth: 25, height: 30 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=400&q=80',
    icon: '❄️',
    description: 'ワンルーム向け6畳用エアコン。省エネ設計でランニングコストを抑えながら快適な室温を維持。',
    style: ['minimal', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'ac-002',
    name: 'エアコン 14畳用 冷暖房',
    category: 'appliance',
    subCategory: 'air_conditioner',
    price: 94800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 80, depth: 25, height: 30 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=400&q=80',
    icon: '❄️',
    description: 'LDKや広めの部屋に対応する14畳用エアコン。空気清浄フィルター内蔵で花粉・PM2.5を除去。',
    style: ['modern'],
    essentialForSingle: false,
  },

  // ───────────────────────────── 掃除機 (2) ────────────────────────────

  {
    id: 'vacuum-001',
    name: 'コードレス掃除機 スリム',
    category: 'appliance',
    subCategory: 'vacuum',
    price: 34800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 25, depth: 25, height: 115 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&q=80',
    icon: '🧹',
    description: '軽量スリムなコードレス掃除機。充電スタンドがそのままインテリアになるデザイン性。',
    style: ['minimal', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'vacuum-002',
    name: 'ロボット掃除機 自動充電',
    category: 'appliance',
    subCategory: 'vacuum',
    price: 42000,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 34, depth: 34, height: 9 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1603712725038-e9334ae8f39f?w=400&q=80',
    icon: '🤖',
    description: '外出中も自動で掃除してくれるロボット掃除機。帰宅したら常にきれいな床。中古でも高性能。',
    style: ['modern'],
    essentialForSingle: false,
  },

  // ───────────────────────────── 炊飯器 (2) ────────────────────────────

  {
    id: 'rice-001',
    name: 'マイコン炊飯器 3合炊き',
    category: 'appliance',
    subCategory: 'rice_cooker',
    price: 8800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 27, depth: 32, height: 21 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&q=80',
    icon: '🍚',
    description: '一人暮らしに最適な3合炊き炊飯器。シンプルな操作で毎日おいしいご飯が炊けます。',
    style: ['minimal'],
    essentialForSingle: false,
  },
  {
    id: 'rice-002',
    name: 'IH炊飯器 5.5合炊き',
    category: 'appliance',
    subCategory: 'rice_cooker',
    price: 27800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 30, depth: 35, height: 24 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1585237017125-24baf8d7406f?w=400&q=80',
    icon: '🍚',
    description: 'IH加熱でおいしく炊けるハイクラス炊飯器。玄米・雑穀米・おかゆモードも搭載。',
    style: ['modern'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ケトル (2) ────────────────────────────

  {
    id: 'kettle-001',
    name: '電気ケトル 0.8L',
    category: 'appliance',
    subCategory: 'kettle',
    price: 3800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 20, depth: 15, height: 22 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?w=400&q=80',
    icon: '🫖',
    description: '0.8Lの電気ケトル。カップ1〜2杯分の湯を素早く沸かせる。軽量で注ぎやすい細口デザイン。',
    style: ['minimal'],
    essentialForSingle: false,
  },
  {
    id: 'kettle-002',
    name: '温度調節ケトル 1.0L',
    category: 'appliance',
    subCategory: 'kettle',
    price: 8200,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 22, depth: 16, height: 25 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80',
    icon: '🫖',
    description: '60℃〜100℃を1℃単位で設定できる温度調節ケトル。緑茶・紅茶・コーヒーに最適温度で。',
    style: ['modern', 'minimal'],
    essentialForSingle: false,
  },

    // ───────────────────────────── ソファ 追加 (4) ─────────────────────────────
  {
    id: 'sofa-007',
    name: '北欧風 2人掛けソファ',
    category: 'furniture',
    subCategory: 'sofa',
    price: 52800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 160, depth: 82, height: 79 },
    color: '#CBB89D',
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=400&q=80',
    icon: '🛋️',
    description: '丸みのあるアームと木脚が特徴の北欧風ソファ。明るい木目調インテリアと相性抜群。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-008',
    name: 'ハイバック リクライニングソファ',
    category: 'furniture',
    subCategory: 'sofa',
    price: 69800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 175, depth: 92, height: 95 },
    color: '#6F747B',
    imageUrl: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=400&q=80',
    icon: '🛋️',
    description: '背もたれ高めで首までしっかり支えるハイバック仕様。映画鑑賞や長時間のくつろぎに。',
    style: ['modern', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-009',
    name: 'カウチソファ コンパクト右肘',
    category: 'furniture',
    subCategory: 'sofa',
    price: 84200,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 195, depth: 135, height: 81 },
    color: '#8C8F7A',
    imageUrl: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=400&q=80',
    icon: '🛋️',
    description: '足を伸ばせるカウチ付きながら比較的省スペース。中古ならではの価格メリットも魅力。',
    style: ['modern', 'natural'],
    essentialForSingle: false,
  },
  {
    id: 'sofa-010',
    name: 'ベルベット調 2人掛けソファ',
    category: 'furniture',
    subCategory: 'sofa',
    price: 61800,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 150, depth: 84, height: 76 },
    color: '#3F4A5A',
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=400&q=80',
    icon: '🛋️',
    description: '上品な光沢感のあるベルベット調生地を採用。ホテルライクな空間づくりにおすすめ。',
    style: ['modern', 'cozy'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ベッド 追加 (4) ─────────────────────────────
  {
    id: 'bed-007',
    name: '脚付きマットレスベッド シングル',
    category: 'furniture',
    subCategory: 'bed',
    price: 29800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 97, depth: 195, height: 42 },
    color: '#F2F2F2',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
    icon: '🛏️',
    description: 'フレーム不要で省スペースに置ける脚付きマットレス。引越し直後の新生活にも便利。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'bed-008',
    name: '宮付き セミダブルベッド',
    category: 'furniture',
    subCategory: 'bed',
    price: 55800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 122, depth: 208, height: 85 },
    color: '#8A6A4A',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80',
    icon: '🛏️',
    description: 'スマホや目覚まし時計を置ける宮棚付き。コンセント内蔵で寝室の使い勝手を高める設計。',
    style: ['natural', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'bed-009',
    name: '跳ね上げ収納ベッド シングル',
    category: 'furniture',
    subCategory: 'bed',
    price: 92800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 100, depth: 210, height: 90 },
    color: '#5A4638',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80',
    icon: '🛏️',
    description: 'ベッド下を全面収納として使える跳ね上げ式。季節家電やスーツケースの収納にも便利。',
    style: ['modern', 'industrial'],
    essentialForSingle: true,
  },
  {
    id: 'bed-010',
    name: 'アイアンフレームベッド ダブル',
    category: 'furniture',
    subCategory: 'bed',
    price: 43800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 145, depth: 205, height: 95 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
    icon: '🛏️',
    description: '無骨なアイアンフレームが映えるダブルベッド。ヴィンテージ感ある部屋づくりに最適。',
    style: ['industrial'],
    essentialForSingle: false,
  },

  // ───────────────────────────── デスク 追加 (4) ─────────────────────────────
  {
    id: 'desk-006',
    name: 'コンパクトPCデスク 90cm',
    category: 'furniture',
    subCategory: 'desk',
    price: 14800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 90, depth: 50, height: 72 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
    icon: '🪵',
    description: 'ノートPCと小物を置くのにちょうど良い省スペースデスク。ワンルームにも置きやすい。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'desk-007',
    name: '収納付きワークデスク',
    category: 'furniture',
    subCategory: 'desk',
    price: 32800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 115, depth: 58, height: 120 },
    color: '#C4A882',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80',
    icon: '🪵',
    description: '天板横に棚収納を備えた多機能デスク。教科書やガジェットを手元にまとめられる。',
    style: ['natural', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'desk-008',
    name: 'ヴィンテージ調 スチールデスク',
    category: 'furniture',
    subCategory: 'desk',
    price: 25800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 120, depth: 60, height: 73 },
    color: '#4A3728',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80',
    icon: '🪵',
    description: '木目天板とブラックフレームの定番ワークデスク。中古でも雰囲気の良い一点。',
    style: ['industrial', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'desk-009',
    name: '引き出し付きデスク 100cm',
    category: 'furniture',
    subCategory: 'desk',
    price: 23800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 100, depth: 55, height: 72 },
    color: '#EDE7DD',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
    icon: '🪵',
    description: '文具やケーブル類をすっきりしまえる引き出し付き。学習用にも在宅ワーク用にも使いやすい。',
    style: ['natural', 'minimal'],
    essentialForSingle: true,
  },

  // ───────────────────────────── チェア 追加 (4) ─────────────────────────────
  {
    id: 'chair-006',
    name: 'アーム付きデスクチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 19800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 61, depth: 58, height: 88 },
    color: '#444444',
    imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=400&q=80',
    icon: '🪑',
    description: '肘掛け付きで作業時の負担を軽減。落ち着いたカラーで書斎空間にもなじみやすい。',
    style: ['modern', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'chair-007',
    name: 'ラタン調ラウンジチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 22400,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 58, depth: 60, height: 79 },
    color: '#C8A87A',
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400&q=80',
    icon: '🪑',
    description: '抜け感のあるラタン調デザインで部屋を軽やかに演出。読書チェアとしてもおすすめ。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'chair-008',
    name: '昇降式スツールチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 9800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 40, depth: 40, height: 48 },
    color: '#A0A0A0',
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80',
    icon: '🪑',
    description: '高さ調整ができるシンプルスツール。キッチンカウンターや作業スペースの補助椅子に便利。',
    style: ['industrial', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'chair-009',
    name: 'ハイバックオフィスチェア',
    category: 'furniture',
    subCategory: 'chair',
    price: 36800,
    condition: 'new',
    shopName: 'インダストリアルホーム',
    size: { width: 64, depth: 62, height: 108 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=400&q=80',
    icon: '🪑',
    description: '背面を大きく支えるハイバック仕様。集中作業やオンライン会議が多い方に向いたモデル。',
    style: ['modern', 'industrial'],
    essentialForSingle: true,
  },

  // ───────────────────────────── ダイニングテーブル 追加 (3) ─────────────────────────────
  {
    id: 'dining-005',
    name: 'バタフライテーブル 90cm',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 34800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 90, depth: 70, height: 72 },
    color: '#D1B08A',
    imageUrl: 'https://images.unsplash.com/photo-1617098474202-0d0d7f60c56b?w=400&q=80',
    icon: '🍽️',
    description: '天板を広げたり畳んだりできるバタフライ式。使わないときはコンパクトに収まる。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'dining-006',
    name: 'カフェ風 丸テーブル 90cm',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 26800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 90, depth: 90, height: 72 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&q=80',
    icon: '🍽️',
    description: '丸天板で動線を邪魔しにくいカフェ風テーブル。2人暮らしや来客時にも使いやすい。',
    style: ['modern', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'dining-007',
    name: '無垢材ダイニングテーブル 140cm',
    category: 'furniture',
    subCategory: 'dining_table',
    price: 64800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 140, depth: 78, height: 72 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1617098474202-0d0d7f60c56b?w=400&q=80',
    icon: '🍽️',
    description: '木の風合いをしっかり感じられる無垢材テーブル。中古ならではの味わいも魅力。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },

  // ───────────────────────────── シェルフ 追加 (3) ─────────────────────────────
  {
    id: 'shelf-005',
    name: 'オープンシェルフ 3段 ワイド',
    category: 'furniture',
    subCategory: 'shelf',
    price: 18800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 120, depth: 32, height: 90 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80',
    icon: '📚',
    description: '見せる収納に向いたワイドタイプのオープンシェルフ。雑貨や本をバランスよく飾れる。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'shelf-006',
    name: 'ガラス扉キャビネット',
    category: 'furniture',
    subCategory: 'shelf',
    price: 29800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 70, depth: 35, height: 140 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=400&q=80',
    icon: '📚',
    description: 'ホコリを防ぎながらお気に入りを見せられるガラス扉タイプ。食器棚としても利用可能。',
    style: ['modern', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'shelf-007',
    name: 'ヴィンテージ調 アイアンラック',
    category: 'furniture',
    subCategory: 'shelf',
    price: 21400,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 85, depth: 34, height: 165 },
    color: '#4A3728',
    imageUrl: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=400&q=80',
    icon: '📚',
    description: '木目棚板とアイアンフレームを組み合わせたラック。無骨すぎず使いやすい定番デザイン。',
    style: ['industrial', 'cozy'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ワードローブ 追加 (3) ─────────────────────────────
  {
    id: 'wardrobe-004',
    name: 'ハンガーラック一体型ワードローブ',
    category: 'furniture',
    subCategory: 'wardrobe',
    price: 22800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 90, depth: 45, height: 175 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
    icon: '🚪',
    description: '扉付き収納とオープンハンガーを組み合わせた実用モデル。見せる収納と隠す収納を両立。',
    style: ['minimal', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'wardrobe-005',
    name: '天然木クローゼット 幅90',
    category: 'furniture',
    subCategory: 'wardrobe',
    price: 49800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 90, depth: 55, height: 190 },
    color: '#C8A87A',
    imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
    icon: '🚪',
    description: 'やわらかな木目が魅力のナチュラルクローゼット。寝室を圧迫しにくい優しい印象。',
    style: ['natural', 'cozy'],
    essentialForSingle: false,
  },
  {
    id: 'wardrobe-006',
    name: 'ミラー付きワードローブ',
    category: 'furniture',
    subCategory: 'wardrobe',
    price: 38800,
    condition: 'used',
    shopName: 'セカンドハンズ家具',
    size: { width: 85, depth: 50, height: 180 },
    color: '#8F8F8F',
    imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
    icon: '🚪',
    description: '全身鏡付きで省スペースに身支度できるワードローブ。ワンルームの収納兼ドレッサー用途に。',
    style: ['modern', 'minimal'],
    essentialForSingle: false,
  },

  // ───────────────────────────── TVスタンド 追加 (3) ─────────────────────────────
  {
    id: 'tvstand-004',
    name: 'コーナーTVボード',
    category: 'furniture',
    subCategory: 'tv_stand',
    price: 19800,
    condition: 'new',
    shopName: 'KAGUERA ストア',
    size: { width: 95, depth: 45, height: 42 },
    color: '#8B6F47',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&q=80',
    icon: '📺',
    description: '部屋の角にすっきり収まるコーナー設計。限られたリビングスペースを有効活用できる。',
    style: ['natural', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'tvstand-005',
    name: 'ハイタイプTVラック',
    category: 'furniture',
    subCategory: 'tv_stand',
    price: 45800,
    condition: 'new',
    shopName: 'モダンリビング',
    size: { width: 120, depth: 40, height: 135 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1615874694520-474822394e73?w=400&q=80',
    icon: '📺',
    description: 'テレビ周りを一体収納できるハイタイプ。DVDや本、小物をまとめて整理しやすい。',
    style: ['modern', 'minimal'],
    essentialForSingle: false,
  },
  {
    id: 'tvstand-006',
    name: 'アイアンフレームTVボード',
    category: 'furniture',
    subCategory: 'tv_stand',
    price: 28800,
    condition: 'used',
    shopName: 'リユース家具ラボ',
    size: { width: 140, depth: 38, height: 45 },
    color: '#3A3A3A',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80',
    icon: '📺',
    description: 'オープン収納中心でAV機器を並べやすい構造。抜け感のある無骨デザインが魅力。',
    style: ['industrial', 'modern'],
    essentialForSingle: false,
  },

  // ───────────────────────────── 冷蔵庫 追加 (3) ─────────────────────────────
  {
    id: 'fridge-005',
    name: '2ドア冷蔵庫 156L マットブラック',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 46800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 52, depth: 60, height: 145 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400&q=80',
    icon: '🧊',
    description: 'キッチン空間を引き締めるマットブラック仕上げ。自炊も外食もバランスよく対応できる容量。',
    style: ['modern', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'fridge-006',
    name: '小型冷蔵庫 90L',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 26800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 48, depth: 50, height: 85 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1536353284924-9220c464e262?w=400&q=80',
    icon: '🧊',
    description: '省スペース重視の90Lモデル。単身赴任や寝室用のセカンド冷蔵庫にも向いている。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'fridge-007',
    name: '観音開き冷蔵庫 420L',
    category: 'appliance',
    subCategory: 'refrigerator',
    price: 138000,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 70, depth: 68, height: 180 },
    color: '#E8E8E8',
    imageUrl: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&q=80',
    icon: '🧊',
    description: 'ファミリー向けの大容量冷蔵庫。冷凍室も広くまとめ買い派に適した高機能モデル。',
    style: ['modern'],
    essentialForSingle: false,
  },

  // ───────────────────────────── テレビ 追加 (3) ─────────────────────────────
  {
    id: 'tv-004',
    name: '32型液晶テレビ',
    category: 'appliance',
    subCategory: 'tv',
    price: 29800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 73, depth: 18, height: 48 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1558888401-3cc1de77652d?w=400&q=80',
    icon: '📺',
    description: 'ワンルームにも置きやすい32型モデル。地デジ・BS・CSに対応したベーシックテレビ。',
    style: ['minimal', 'modern'],
    essentialForSingle: false,
  },
  {
    id: 'tv-005',
    name: '50型 4Kスマートテレビ',
    category: 'appliance',
    subCategory: 'tv',
    price: 79800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 112, depth: 25, height: 71 },
    color: '#111111',
    imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400&q=80',
    icon: '📺',
    description: '動画配信アプリを手軽に楽しめる4Kスマートテレビ。映画やスポーツ観戦に最適。',
    style: ['modern'],
    essentialForSingle: false,
  },
  {
    id: 'tv-006',
    name: '43型液晶テレビ 中古美品',
    category: 'appliance',
    subCategory: 'tv',
    price: 39800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 97, depth: 22, height: 63 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&q=80',
    icon: '📺',
    description: 'コストを抑えつつ十分な画面サイズを確保できる43型中古モデル。初めての一台にも。',
    style: ['modern', 'minimal'],
    essentialForSingle: false,
  },

  // ───────────────────────────── 電子レンジ 追加 (3) ─────────────────────────────
  {
    id: 'microwave-004',
    name: '単機能電子レンジ 17L ブラック',
    category: 'appliance',
    subCategory: 'microwave',
    price: 9800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 45, depth: 35, height: 26 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=400&q=80',
    icon: '📦',
    description: '温め機能に特化したシンプル操作の電子レンジ。ブラックカラーで家電を統一したい方に。',
    style: ['minimal', 'modern'],
    essentialForSingle: true,
  },
  {
    id: 'microwave-005',
    name: 'オーブンレンジ 20L ホワイト',
    category: 'appliance',
    subCategory: 'microwave',
    price: 16800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 47, depth: 39, height: 30 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&q=80',
    icon: '📦',
    description: '温めに加えて簡単な焼き調理も可能なオーブンレンジ。トーストやグラタンにも対応。',
    style: ['modern', 'minimal'],
    essentialForSingle: true,
  },
  {
    id: 'microwave-006',
    name: 'フラットテーブル電子レンジ 中古',
    category: 'appliance',
    subCategory: 'microwave',
    price: 11800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 46, depth: 37, height: 28 },
    color: '#EDEDED',
    imageUrl: 'https://images.unsplash.com/photo-1585237017125-24baf8d7406f?w=400&q=80',
    icon: '📦',
    description: 'ターンテーブルがなく庫内を拭きやすいフラットタイプ。コスパ重視の中古モデル。',
    style: ['minimal'],
    essentialForSingle: true,
  },

  // ───────────────────────────── 洗濯機 追加 (3) ─────────────────────────────
  {
    id: 'wash-004',
    name: '全自動洗濯機 5kg コンパクト',
    category: 'appliance',
    subCategory: 'washing_machine',
    price: 39800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 52, depth: 50, height: 89 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400&q=80',
    icon: '🫧',
    description: '幅を抑えたコンパクト設計で防水パンにも置きやすい。単身者向けのベーシックモデル。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'wash-005',
    name: '縦型洗濯乾燥機 7kg',
    category: 'appliance',
    subCategory: 'washing_machine',
    price: 72800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 57, depth: 59, height: 98 },
    color: '#F5F5F5',
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&q=80',
    icon: '🫧',
    description: '洗濯から簡易乾燥まで一台で対応。天候が不安定な季節の部屋干し負担を軽減する。',
    style: ['modern'],
    essentialForSingle: true,
  },
  {
    id: 'wash-006',
    name: 'ドラム式洗濯機 10kg 中古',
    category: 'appliance',
    subCategory: 'washing_machine',
    price: 89800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 64, depth: 68, height: 102 },
    color: '#DDDDDD',
    imageUrl: 'https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?w=400&q=80',
    icon: '🫧',
    description: '大容量ドラム式を中古価格で導入できる一台。まとめ洗いが多い家庭にも向いている。',
    style: ['modern'],
    essentialForSingle: false,
  },

  // ───────────────────────────── エアコン 追加 (3) ─────────────────────────────
  {
    id: 'aircon-003',
    name: '6畳用 エアコン スタンダード',
    category: 'appliance',
    subCategory: 'air_conditioner',
    price: 49800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 78, depth: 23, height: 28 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=400&q=80',
    icon: '❄️',
    description: '寝室やワンルームにちょうど良い6畳向けモデル。基本機能をしっかり備えた定番エアコン。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'aircon-004',
    name: '10畳用 省エネエアコン',
    category: 'appliance',
    subCategory: 'air_conditioner',
    price: 79800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 80, depth: 25, height: 29 },
    color: '#F8F8F8',
    imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=400&q=80',
    icon: '❄️',
    description: 'リビングにも対応しやすい10畳モデル。節電モード搭載で年間の電気代を抑えやすい。',
    style: ['modern'],
    essentialForSingle: false,
  },
  {
    id: 'aircon-005',
    name: '8畳用 エアコン 中古標準モデル',
    category: 'appliance',
    subCategory: 'air_conditioner',
    price: 39800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 77, depth: 24, height: 28 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=400&q=80',
    icon: '❄️',
    description: '初期費用を抑えたい方向けの中古エアコン。必要十分な冷暖房性能を確保した実用モデル。',
    style: ['minimal'],
    essentialForSingle: true,
  },

  // ───────────────────────────── 掃除機 追加 (3) ─────────────────────────────
  {
    id: 'vacuum-003',
    name: 'スティッククリーナー 軽量モデル',
    category: 'appliance',
    subCategory: 'vacuum',
    price: 12800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 25, depth: 20, height: 110 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80',
    icon: '🧹',
    description: '取り回しやすい軽量スティックタイプ。毎日のちょい掃除に使いやすい一台。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'vacuum-004',
    name: 'コードレス掃除機 ハイパワー',
    category: 'appliance',
    subCategory: 'vacuum',
    price: 32800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 26, depth: 22, height: 115 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&q=80',
    icon: '🧹',
    description: '吸引力を重視したコードレスモデル。フローリングからラグまで幅広く対応する。',
    style: ['modern'],
    essentialForSingle: true,
  },
  {
    id: 'vacuum-005',
    name: 'キャニスター掃除機 中古',
    category: 'appliance',
    subCategory: 'vacuum',
    price: 9800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 32, depth: 24, height: 26 },
    color: '#D9D9D9',
    imageUrl: 'https://images.unsplash.com/photo-1603712725038-e9334ae8f39f?w=400&q=80',
    icon: '🧹',
    description: '安定した吸引力で根強い人気のキャニスター型。価格重視で選びたい方におすすめ。',
    style: ['minimal'],
    essentialForSingle: true,
  },

  // ───────────────────────────── 炊飯器 追加 (3) ─────────────────────────────
  {
    id: 'rice-003',
    name: 'マイコン炊飯器 3合炊き',
    category: 'appliance',
    subCategory: 'rice_cooker',
    price: 7800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 24, depth: 28, height: 20 },
    color: '#FFFFFF',
    imageUrl: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&q=80',
    icon: '🍚',
    description: '少量炊きに向いた3合モデル。新生活の初期費用を抑えたい方にぴったり。',
    style: ['minimal'],
    essentialForSingle: true,
  },
  {
    id: 'rice-004',
    name: '圧力IH炊飯器 5.5合',
    category: 'appliance',
    subCategory: 'rice_cooker',
    price: 34800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 29, depth: 36, height: 25 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&q=80',
    icon: '🍚',
    description: '圧力IHでふっくら炊き上げる上位モデル。ご飯の味にこだわる自炊派向け。',
    style: ['modern'],
    essentialForSingle: false,
  },
  {
    id: 'rice-005',
    name: '炊飯器 5合炊き 中古',
    category: 'appliance',
    subCategory: 'rice_cooker',
    price: 12800,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 27, depth: 32, height: 23 },
    color: '#E5E5E5',
    imageUrl: 'https://images.unsplash.com/photo-1585237017125-24baf8d7406f?w=400&q=80',
    icon: '🍚',
    description: '家庭用として使いやすい5合炊き中古モデル。コスパ重視のまとめ炊きにも向いている。',
    style: ['minimal'],
    essentialForSingle: false,
  },

  // ───────────────────────────── ケトル 追加 (3) ─────────────────────────────
  {
    id: 'kettle-003',
    name: 'ガラス電気ケトル 1.2L',
    category: 'appliance',
    subCategory: 'kettle',
    price: 5200,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 21, depth: 16, height: 24 },
    color: '#CFE8FF',
    imageUrl: 'https://images.unsplash.com/photo-1510627489930-0c1b0bfb6785?w=400&q=80',
    icon: '🫖',
    description: '中身が見やすいガラスボディの電気ケトル。来客時や食卓での使用にも映えるデザイン。',
    style: ['modern'],
    essentialForSingle: false,
  },
  {
    id: 'kettle-004',
    name: '細口ドリップケトル 0.9L',
    category: 'appliance',
    subCategory: 'kettle',
    price: 6800,
    condition: 'new',
    shopName: 'カグエラ 家電館',
    size: { width: 28, depth: 14, height: 20 },
    color: '#222222',
    imageUrl: 'https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?w=400&q=80',
    icon: '🫖',
    description: '湯量をコントロールしやすい細口ノズルを採用。コーヒー好きの一人暮らしに人気。',
    style: ['minimal', 'industrial'],
    essentialForSingle: false,
  },
  {
    id: 'kettle-005',
    name: '電気ケトル 1.0L 中古',
    category: 'appliance',
    subCategory: 'kettle',
    price: 2900,
    condition: 'used',
    shopName: 'リユース家電センター',
    size: { width: 20, depth: 15, height: 23 },
    color: '#F2F2F2',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80',
    icon: '🫖',
    description: '必要十分な機能を備えたシンプルな中古ケトル。新生活の初期コスト削減に役立つ。',
    style: ['minimal'],
    essentialForSingle: false,
  },
];

// ============================================================
// ユーティリティ
// ============================================================

/** カテゴリでフィルタ */
export function filterByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

/** サブカテゴリでフィルタ */
export function filterBySubCategory(sub: SubCategory): Product[] {
  return products.filter((p) => p.subCategory === sub);
}

/** スタイルでフィルタ */
export function filterByStyle(style: Style): Product[] {
  return products.filter((p) => p.style.includes(style));
}

/** 一人暮らし必需品のみ */
export function getEssentials(): Product[] {
  return products.filter((p) => p.essentialForSingle);
}

/** IDで1件取得 */
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

/** 件数サマリ（デバッグ用） */
export function countBySubCategory(): Record<SubCategory, number> {
  return products.reduce(
    (acc, p) => {
      acc[p.subCategory] = (acc[p.subCategory] ?? 0) + 1;
      return acc;
    },
    {} as Record<SubCategory, number>,
  );
}
